### ISSUE TITLE
build ESP for Android

### ISSUE THREAD

**Issue by RimeOCRLIB** [embedthis/esp#103]
Good day. 
For mobile application project we need build ESP core framework for Android.
We successfully has compiled ESP and libraries binary by make script from cross-platform ESP source code esp 8.1.0
compiler - clung under C4Drod or under Termux (both compiler has the same results)

Result esp program is arm64 architecture  and linked with all libraries (libesp,libhttp etc.)

Problem is we are not able start mprCreate(...)
The empty main function in esp.c work fine, but we have Segmentation Fault after start mprCreate()

For Android compilation in makefile we was forced remove -lrt and -lpthread libraries.
https://stackoverflow.com/questions/38666609/cant-find-lpthread-when-cross-compile-to-arm
Another addition to makefile was only
ARCH:=arm64
OS:=linux
CXX=arm-linux-androideabi-g++

Look like the thread implementation is slightly different under arm64? 
We may try to debug mprCreate() and detect problem more precisely.

Any advice or another help will be really appreciated.

Alexander Stroganov
Open Source Buddhism Library
www.buddism.ru

**Comment by dev-embedthis** [comment]
Thanks for reporting.

I think the fix for ARM 64 is to change osdep.h


```
diff --git a/dist/osdep.h b/dist/osdep.h
index 1b90753..423c85a 100644
--- a/dist/osdep.h
+++ b/dist/osdep.h
@@ -242,7 +242,7 @@

 #endif

-#if __WORDSIZE == 64 || __amd64 || __x86_64 || __x86_64__ || _WIN64 || __mips64 || __arch64__ || __arm64__
+#if __WORDSIZE == 64 || __amd64 || __x86_64 || __x86_64__ || _WIN64 || __mips64 || __arch64__ || __arm64__ || __aarch64__
     #define ME_64 1
     #define ME_WORDSIZE 64
```

**Comment by RimeOCRLIB** [comment]
Good day.
We have corrected this osdep.h header and here it is esp for Android ARM build update.

1. We was no t able build MakeMe for arm.
output is:
`$ ARCH=arm make boot
      [Info] Use make SHOW=1 to trace executed commands.
      [Copy] build/linux-arm-default/inc/osdep.h
      [Copy] build/linux-arm-default/inc/embedtls.h
      [Copy] build/linux-arm-default/inc/mbedtls-config.h
      [Copy] build/linux-arm-default/inc/mbedtls.h
   [Compile] build/linux-arm-default/obj/mbedtls.o
      [Link] build/linux-arm-default/bin/libmbedtls.a
      [Copy] build/linux-arm-default/inc/mpr.h
   [Compile] build/linux-arm-default/obj/mpr-mbedtls.o
      [Link] build/linux-arm-default/bin/libmpr-mbedtls.a
      [Copy] build/linux-arm-default/inc/zlib.h
   [Compile] build/linux-arm-default/obj/zlib.o
      [Link] build/linux-arm-default/bin/libzlib.so
   [Compile] build/linux-arm-default/obj/mprLib.o
      [Link] build/linux-arm-default/bin/libmpr.so
      [Copy] build/linux-arm-default/inc/pcre.h
   [Compile] build/linux-arm-default/obj/pcre.o
      [Link] build/linux-arm-default/bin/libpcre.so
      [Copy] build/linux-arm-default/inc/http.h
   [Compile] build/linux-arm-default/obj/httpLib.o
      [Link] build/linux-arm-default/bin/libhttp.so
      [Copy] build/linux-arm-default/inc/ejs.h
      [Copy] build/linux-arm-default/inc/ejs.slots.h
      [Copy] build/linux-arm-default/inc/ejsByteGoto.h
   [Compile] build/linux-arm-default/obj/ejsLib.o
      [Link] build/linux-arm-default/bin/libejs.so
   [Compile] build/linux-arm-default/obj/ejsc.o
      [Link] build/linux-arm-default/bin/makeme-ejsc
   [Compile] ejs.mod
make[1]: *** [projects/makeme-linux-default.mk:807: build/linux-arm-default/bin/ejs.mod] Segmentation fault
make: *** [Makefile:64: boot] Error 2`

2. On reason we was not able build MakeMe we was forced use default linux configuration for arm processor.
May be it is really need run MakeMe configure first.

3. we was not able to build esp-master source code from GitHub emedthis repository.
make give us a lot of errors:
`src/mpr/mprLib.c:16676:13: error: conflicting types for 'mprSetCmdlineLogging'
PUBLIC bool mprSetCmdlineLogging(bool on)
            ^
src/mpr/mpr.h:10329:13: note: previous declaration is here
PUBLIC bool mprSetCmdlineLogging(bool on);
            ^
src/mpr/mprLib.c:16689:13: error: conflicting types for 'mprGetCmdlineLogging'
PUBLIC bool mprGetCmdlineLogging()
            ^
src/mpr/mpr.h:10054:13: note: previous declaration is here
PUBLIC bool mprGetCmdlineLogging(void);
            ^
src/mpr/mprLib.c:18706:13: error: conflicting types for 'mprMatchPath'
PUBLIC bool mprMatchPath(cchar *path, cchar *pattern)
....
`

3. For default linux arm settings we was able to build esp-8.1.0 source code from embedthis.com main site
this code can not start main soket-server and under GDP give us this massage:

`
Program received signal SIGSEGV, Segmentation fault.
0x0000007fb7906d4c in pthread_mutex_trylock () from /system/lib64/libc.so
(gdb)
`
another ESP libraries which is not use threads look fine.

Any help will be really appreciate. We have in 2020 work plan to use ESP for linguistic portal for about 250 languages linguistic data for small nations. Many this national languages are in danger to disappear and have beautiful cultures.

Thank you from my heart for all your efforts for ESP community.
Open Source Buddhism Library 
www.buddism.ru
Alexander Stroganov

**Comment by RimeOCRLIB** [comment]
update a Android build result. 
We have installed Linux on Android + clang 10.
As result of build we have aarch64 ESP binary for linux-aarch64-default
without any compilation error.

Unfortunately we still have segmentation fault error.
GDB print the message:
`During startup program exited with code 182`

This time we was able compile MakeMe (only from GitHub, not from site download link)
All this ESP main build was builded with "me configure" and "me build" 

Any idea that it is need to do?

With best regards
Alexander Stroganov

**Comment by dev-embedthis** [comment]
Can you retry with the current master branch which is version 9.0.0?

**Comment by RimeOCRLIB** [comment]
Great.

We was able build ESP 9.0.0 under Android Ubuntu (UserLAnd emulator)
It is only one diff -
http/server.c  201
app->signal = mprAddSignalHandler(SIGINFO, showState, 0, 0, MPR_SIGNAL_AFTER);
in Android
app->signal = mprAddSignalHandler(SIGIPRW, showState, 0, 0, MPR_SIGNAL_AFTER); 

SIGINFO and SIGIPRW are the same signal
https://unix.stackexchange.com/questions/179481/siginfo-on-gnu-linux-arch-linux-missing

On next step we will try to build ESP 9.0.0 under Android NDK. In that case ESP would work as native android application.

For now it is lot of error in mor/mprLib.c

`src/mpr/mprLib.c:5161:13: error: conflicting types for 'mprRemoveCache'
PUBLIC bool mprRemoveCache(MprCache *cache, cchar *key)
            ^
src/mpr/mpr.h:9611:13: note: previous declaration is here
PUBLIC bool mprRemoveCache(MprCache *cache, cchar *key);
            ^
src/mpr/mprLib.c:6200:13: error: conflicting types for 'mprAreCmdEventsEnabled'
PUBLIC bool mprAreCmdEventsEnabled(MprCmd *cmd, int channel)
            ^
src/mpr/mpr.h:9111:13: note: previous declaration is here
PUBLIC bool mprAreCmdEventsEnabled(MprCmd *cmd, int channel);
            ^
src/mpr/mprLib.c:6212:13: error: conflicting types for 'mprEnableCmdOutputEvents'
PUBLIC void mprEnableCmdOutputEvents(MprCmd *cmd, bool on)
            ^
src/mpr/mpr.h:9173:13: note: previous declaration is here
PUBLIC void mprEnableCmdOutputEvents(MprCmd *cmd, bool on);
            ^
src/mpr/mprLib.c:6547:13: error: conflicting types for 'mprIsCmdRunning'
PUBLIC bool mprIsCmdRunning(MprCmd *cmd)
            ^
src/mpr/mpr.h:9236:13: note: previous declaration is here
PUBLIC bool mprIsCmdRunning(MprCmd *cmd);
            ^`

**Comment by dev-embedthis** [comment]
FYI: use three backticks to format code properly. ;-)

**Comment by dev-embedthis** [comment]
You'll have to dig into the compiler definitions because those messages above show the definition being exactly the same as the use. The mpr.h and mprLib.c definitions match exactly.

Can you do

make SHOW=1

to see the command lines and post the relevant one here.

Then change -c to -E and capture the output when you run gcc stand-alone. Then look in that pre-processed file to see what is causing the compiler error.

**Comment by RimeOCRLIB** [comment]
From my heart thank you for help.
ESP is marvelous for c/c++ server development and we are happy to continue use it under ARM

For Android NDK it will be need test few building environment. At present this is mere question for limited C implementation on Android (no glob, getpass, ffsl ...).
As long as we have succesfully build ESP for aarch64 Android Ubunty it is just need some efforts to build ESP under Android NDK. We was already have mprLib.c builded under another build environment (but need add getpass and another function to this environment). We will post result of build in this thread after some time.

Thank you again for your kind help.

Send you all the best wishes and regards from team of our library.
Alexander Stroganov
Open Source Buddhism Library
www.buddism.ru

**Comment by RimeOCRLIB** [comment]
In base Android operation system very limited pthread library support
https://stackoverflow.com/questions/30801752/android-ndk-and-pthread
```
POSIX threads (pthreads)
The android libc, bionic, provides built-in support for pthreads, so no
additional linking (-lpthreads) is necessary. It does not implement full
POSIX threads functionality and leaves out support for read/write locks,
pthread_cancel(), process-shared mutexes and condition variables as well as
other more advanced features. Read the bionic OVERVIEW.txt for more
information.
```
http://www.dre.vanderbilt.edu/~schmidt/android/android-4.0/bionic/libc/docs/OVERVIEW.TXT

We was able successfully build and run ESP under Ubuntu on Xiomi MiPad 4 
But for present was failed to build ESP under native Android NDK.
If we will be have additional information we will add it here.

Send you all the best wishes from our team.
Alexander
