### ISSUE TITLE
vc2019 not find __ATOMIC_ACQUIRE

### ISSUE THREAD

**Issue by linia** [embedthis/esp#105]
error C2065: “__ATOMIC_ACQUIRE”: 未声明的标识符

**Comment by linia** [comment]
#define __ATOMIC_RELAXED 1
#define __ATOMIC_CONSUME 1
#define __ATOMIC_ACQUIRE 1
#define __ATOMIC_RELEASE 1
#define __ATOMIC_ACQ_REL 1
#define __ATOMIC_SEQ_CST 1

**Comment by mobsense** [comment]
Fix committed.
