### ISSUE TITLE
how to use ajax post

### ISSUE THREAD

**Issue by may2250** [embedthis/esp#61]
in version 5.2.0. i use jquery.ajax post with an error of 401 -- Unauthorized
$.ajax({
                    type: "POST",
                    async: false,
                    url: "http://"+localip+":4000/do/programs/uploads",
                    data: JSON.parse(paramjson),
                    dataType: "json",
                    success: function(data){
                        if(data.sts == 8){
                            window.location = "/login.esp";
                        }else if(data.sts == 5){
                            
                            return false;
                        }
                          
                    },
                    error : function(err) {
                        alert("AJAX ERROR---uploads!!");
                    }
                });
when i use type:"get", there is no problem; 
i think i should use 
    var token = <%= securityToken(); %>;
but it not work and it is wrong in js. I've no idea now. Pls help me, thanks!!

**Comment by embedthis** [comment]
See how to submit an issue:

https://github.com/embedthis/esp/issues/32

Need full http headers and a test case.
