### ISSUE TITLE
Database accessing 

### ISSUE THREAD

**Issue by ethanwortho** [embedthis/esp#75]
i understand this is not an issue but the link to the ESP support forum (google group) says the group does not exist.

Im reasonably new to web page design so bare with me, im looking to use the esp frame work to create an interface to access an sqlite database for a project im working on where i will need to read values from and put them into a table on the webpage, and also write values back to the database.

i have read through the esp documentation online and tried to use  the direct api access method using 

<p>Price: <%= ediGetField(product, "price"); </p>

how ever i get an error in esp saying that product is undeclared and this is the first time its seen. i have 

"database": "sdb://demp.sdb" in my esp.json and
"database": "db" in my package.json 

is there anything i am missing or am i going about this all wrong? i have looked at the examples for the blog post and login forms from the dev branch but neither work when i try to run them

thanks

**Comment by mobrien** [comment]
The embedded code is C code. So there needs to exist a product variable.
That API, the product must be an EdiRec reference.
