### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by TheDharc** [embedthis/esp#78]
Hi, is esp still alive?

**Comment by mobrien** [comment]
Sure is. Embedded in appweb and used heavily.

**Comment by TheDharc** [comment]
@mobrien can i use it for commercial systems like e-commerce, erp, etc?

**Comment by mobrien** [comment]
Sure. It is agnostic for the end application.

But their may be frameworks better suited for enterprise applications.

This is primarily for embedded.

**Comment by TheDharc** [comment]
May you choose another license for the open source version? GPL doesn't meet the need for all use cases. Another copyleft license like MPL 2.0 embraces more use cases. Or Apache license.

**Comment by mobrien** [comment]
Embedthis sells commercial licenses for those other needs. GPL is essential to the business model to be able to fund the development and provide support.
