### ISSUE TITLE
esp upload by POST,appears HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by DennisYsj** [embedthis/esp#79]
Request URL:
    http://127.0.0.1:8080/espapp/camera/upload.esp 
    Request Method:
    POST
    Status Code:
    HTTP/1.1 401 Unauthorized

**Comment by mobrien** [comment]
You get a 401 when you have defined authorization requirements in the appweb.conf but the request does not submit any authentication headers.

**Comment by DennisYsj** [comment]
May I ask how to solve it?``
this is my appweb.conf
`#
#   appweb.conf -- Appweb configuration for espapp
#
ErrorLog stdout level=2 append
# TraceLog trace.log level=4 size=10MB backup=5 anew

Listen 127.0.0.1:8080
<if ESP_MODULE>
    AddHandler espHandler esp
    EspApp prefix="/"       config="./esp.json"
    AuthType none
</if>
**this is my controllers upload.c**
#include "esp.h"
/*
    Create a new resource in the database
 */ 
static void createUpload() { 
    renderView("upload/upload-form");
}

static void redirectUpload() {
    redirect(sjoin(getUri(), "/", NULL));
}

static void commonUpload(HttpConn *conn) {
}

/*
    Dynamic module initialization
 */
ESP_EXPORT int esp_controller_espapp_upload(HttpRoute *route, MprModule *module) {
    espDefineBase(route, commonUpload);
    espDefineAction(route, "upload/", createUpload);
    espDefineAction(route, "upload", redirectUpload);
    return 0;
}
this is my upload folder,it contains upload-form.esp and upload.esp.
upload-form.esp
<html>
<head>
<title>ESP Upload</title>
</head>
<body>
    <h2>ESP File Upload</h2>
    
    <form method="post" action="/upload/upload.esp" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="30000">
        <table border="0">
            <tr><td>Name</td><td><input type="text" name="Name"></td></tr>
            <tr><td>Address</td><td><input type="text" name="Address"></td></tr>
            <tr><td>Photo:</td><td><input type="file" name="photo"></td></tr>
        </table>
        <input type="submit" value="send">
        <input type="reset" value="cancel">
    </form>
</body>
</html>
this is my upload.esp
<html><head><title>upload.esp</title></head>
<body>
    <pre><% {
        HttpConn        *conn;
        HttpUploadFile  *file;
        MprKey          *kp;
        int             index;

        /*
            File upload permits multiple files. Iterate over all uploaded files.
            The file is uploaded to a temporary file file->filename. The original
            client filename is file->clientFilename. This page should copy, move
            or process the temporary file. The temporary will be automatically 
            removed when this page completes.

            The reason for using a temporary is that multiple clients may upload
            a file with the same filename at the same time. Temporary filenames
            are unique and solve potential conflicts.
         */
        conn = getConn();
        for (ITERATE_ITEMS(conn->rx->files, file, index)) {
            render("NAME %s\n", file->name);
            render("FILENAME %s\n", file->filename);
            render("CLIENT_NAME %s\n", file->clientFilename);
            render("TYPE %s\n", file->contentType);
            render("SIZE %d\n", file->size);
        }
    } %></pre>
    <pre>
        <% showRequest(); %>
    </pre>
</body>
</html>

**Comment by DennisYsj** [comment]
**How can I solve?**
**this is my appweb.conf**
`#
#   appweb.conf -- Appweb configuration for espapp
#
ErrorLog stdout level=2 append
# TraceLog trace.log level=4 size=10MB backup=5 anew

Listen 127.0.0.1:8080
<if ESP_MODULE>
    AddHandler espHandler esp
    EspApp prefix="/"       config="./esp.json"
    AuthType none
</if>
`
**this is my controllers upload.c**
`/*
    upload Controller (esp-html-skeleton)
 */
#include "esp.h"
/*
    Create a new resource in the database
 */ 
static void createUpload() { 
    renderView("upload/upload-form");
}

static void redirectUpload() {
    redirect(sjoin(getUri(), "/", NULL));
}

static void commonUpload(HttpConn *conn) {
}

/*
    Dynamic module initialization
 */
ESP_EXPORT int esp_controller_espapp_upload(HttpRoute *route, MprModule *module) {
    espDefineBase(route, commonUpload);
    espDefineAction(route, "upload/", createUpload);
    espDefineAction(route, "upload", redirectUpload);
    return 0;
}
`
**this is my upload folder, upload-form.esp and upload.esp**
upload-form.esp
`<html>
<head>
<title>ESP Upload</title>
</head>
<body>
    <h2>ESP File Upload</h2>
    
    <form method="post" action="/upload/upload.esp" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="30000">
        <table border="0">
            <tr><td>Name</td><td><input type="text" name="Name"></td></tr>
            <tr><td>Address</td><td><input type="text" name="Address"></td></tr>
            <tr><td>Photo:</td><td><input type="file" name="photo"></td></tr>
        </table>
        <input type="submit" value="send">
        <input type="reset" value="cancel">
    </form>
</body>
</html>`
**this is my upload.esp**
`<html><head><title>upload.esp</title></head>
<body>
    <pre><% {
        HttpConn        *conn;
        HttpUploadFile  *file;
        MprKey          *kp;
        int             index;

        /*
            File upload permits multiple files. Iterate over all uploaded files.
            The file is uploaded to a temporary file file->filename. The original
            client filename is file->clientFilename. This page should copy, move
            or process the temporary file. The temporary will be automatically 
            removed when this page completes.

            The reason for using a temporary is that multiple clients may upload
            a file with the same filename at the same time. Temporary filenames
            are unique and solve potential conflicts.
         */
        conn = getConn();
        for (ITERATE_ITEMS(conn->rx->files, file, index)) {
            render("NAME %s\n", file->name);
            render("FILENAME %s\n", file->filename);
            render("CLIENT_NAME %s\n", file->clientFilename);
            render("TYPE %s\n", file->contentType);
            render("SIZE %d\n", file->size);
        }
    } %></pre>
    <pre>
        <% showRequest(); %>
    </pre>
</body>
</html>
`

**Comment by DennisYsj** [comment]
This is my appweb.conf, how can I configure it？
 
#   appweb.conf -- Appweb configuration for espapp
ErrorLog stdout level=2 append
# TraceLog trace.log level=4 size=10MB backup=5 anew
Listen 127.0.0.1:8080
<if ESP_MODULE>
    AddHandler espHandler esp
    EspApp prefix="/"       config="./esp.json"
    AuthType none
</if>

**Comment by DennisYsj** [comment]
This is my appweb.conf, how can I configure it?

ErrorLog stdout level=2 append

Listen 127.0.0.1:8080
<if ESP_MODULE>
    AddHandler espHandler esp
    EspApp prefix="/"       config="./esp.json"
    AuthType none
</if>

**Comment by mobrien** [comment]
Tested this and did not get a 401. Can you post your esp.json?
