### ISSUE TITLE
appweb+esp file upload appears Access Error: 401 -- Unauthorized

### ISSUE THREAD

**Issue by DennisYsj** [embedthis/esp#80]
Linux, appweb + esp file upload (post ) appears Access Error: 401 -- Unauthorized
Security token is stale. Please reload page., but the esp sample alone will not be this phenomenon。Troubled for a long time, please help me, thank you！！！

**Comment by mobrien** [comment]
Need more details. Please include esp HTTP header logs and a test case to reproduce.

**Comment by mobrien** [comment]
Can you post more details. See "How to submit an issue" https://github.com/embedthis/esp/issues/32

Need to see what esp sample you are running.
