### ISSUE TITLE
Missing dependencies in esp-html-skeleton

### ISSUE THREAD

**Issue by MaskedVII** [embedthis/esp#81]
Starting with ESP installed with make no flags, following the docs when type:

$ pak install esp-html-skeleton

The output is:

Cannot locate package "exp-canon" ~0.1
Cannot cache esp-mvc because of missing required dependency "exp-canon"
pak: ERROR: Cannot cache esp-html-skeleton because of missing required dependency "esp-mvc"

In the docs are no references to additional packages, trying to install by hand but theres no references in pak, bower or npm, I really want to learn this so any help will be apreciated

**Comment by mobrien** [comment]
If you edit pak.json and change the exp-canon version to 0.3 it will work.

We'll fix this in the next few days.

**Comment by MaskedVII** [comment]
Thx for the fix, where to go for help? theres no support, forum, blog here or in ESP pages... the API and docs looks good, but always are more questions

**Comment by mobrien** [comment]
Embedthis offers commercial licenses and support.
Bug issues can be logged here.
If you ask questions that are not answered in the doc, please ask here and we'll update the doc to be more complete.

**Comment by mobrien** [comment]
Fixed and will be released over the next day as part of an esp update.

**Comment by MaskedVII** [comment]
Thanks that was a quick responsable approach, cya
