### ISSUE TITLE
How can I use esp compile?

### ISSUE THREAD

**Issue by abner-xie** [embedthis/esp#82]
I use command: esp -r compile, and compile success, like this:
maxm@ubuntu:~/thirdlib/esp-7.0.2/samples/controller$ esp -r compile
   [Compile] service.c
Then I run the esp, all is ok, the http service is started.
maxm@ubuntu:~/thirdlib/esp-7.0.2/samples/controller$ esp
Started HTTP service on 127.0.0.1:4000

But now I want to add another C file, example db.c, some functions in db.c is invoked by service.c. I put the db.c and db.h in this directory.
maxm@ubuntu:~/thirdlib/esp-7.0.2/samples/controller$ ls
db.c  db.h  esp.json  README.md  service.c

Then I compile and run esp, but occurs a error below.

maxm@ubuntu:~/thirdlib/esp-7.0.2/samples/controller$ esp -r compile
   [Compile] service.c
maxm@ubuntu:~/thirdlib/esp-7.0.2/samples/controller$ esp
Started HTTP service on 127.0.0.1:4000
esp: symbol lookup error: /home/maxm/thirdlib/esp-7.0.2/samples/controller/cache/controller_8088a587224a8a92482c34c4498f7e67.so: undefined symbol: db_init

How can I resolve this error?

**Comment by dev-embedthis** [comment]
When you invoke "esp compile", it will compile several directories for each configured route. It will look for controllers/*.c, views/*.c documents/*.esp and src/app.c.

* controllers
* documents
* views
* src/app.c

If you are compiling in combined mode, these will be linked into a single shared library. This is ideal for production. For development on linux or windows, you compile in discrete mode where each file is made into a separate shared library that can be dynamically reloaded if the source is modified.

You have a few options. You can compile your C files (non *.esp files) yourself into a shared library and then link with those files by passing in the library via CFLAGS or LDFLAGS to "esp compile".

```
CFLAGS=`-lmylib` esp compile
```

The other option is to include other source files from app.c. This way app.c becomes your master source file and it includes all other relevant source files.

**Comment by abner-xie** [comment]
I see, We appreciate your help and your patience.




| |
abner_xie
邮箱：abner_xie@yeah.net
|

Signature is customized by Netease Mail Master

On 10/23/2018 13:16, Embedthis Development wrote:

When you invoke "esp compile", it will compile several directories for each configured route. It will look for controllers/.c, views/.c documents/*.esp and src/app.c.

controllers
documents
views
src/app.c

If you are compiling in combined mode, these will be linked into a single shared library. This is ideal for production. For development on linux or windows, you compile in discrete mode where each file is made into a separate shared library that can be dynamically reloaded if the source is modified.

You have a few options. You can compile your C files (non *.esp files) yourself into a shared library and then link with those files by passing in the library via CFLAGS or LDFLAGS to "esp compile".

CFLAGS=`-lmylib` esp compile


The other option is to include other source files from app.c. This way app.c becomes your master source file and it includes all other relevant source files.
