### ISSUE TITLE
Cross origin requests

### ISSUE THREAD

**Issue by derekibw** [embedthis/esp#85]
Our project is separate from the web and server. The backend uses the esp development API for the web. The developers use different servers. The use of ajax requests has cross-domain problems. What is the solution for the server? I tried adding headers in http of esp.json as follows:

"headers": {
	    "add": {
		'Content-Security-Policy': 'allow "*"; unsafe-inline; img-src "*"',
		'Access-Control-Allow-Origin': '*',
		'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
		'Access-Control-Allow-Headers': 'X-Custom-Header',
		'Access-Control-Allow-Credentials': true
		'Access-Control-Max-Age': 1728000
	    }
	},

I have been unable to solve it for a long time. Does ESP provide related solutions?

**Comment by dev-embedthis** [comment]
More details needed. Are you having trouble getting the headers emitted?
