### ISSUE TITLE
include c++ code in ESP as dynamic library

### ISSUE THREAD

**Issue by RimeOCRLIB** [embedthis/esp#86]
Good day. 
For buddhist knowledge base project we need stable connection between database and OCR c++ core and ESP. [https://github.com/RimeOCRLIB/OCRLib](https://github.com/RimeOCRLIB/OCRLib)
At present we have linked compiled OCR and database core to ESP as dynamic library.
This way ESP calls about 50 functions of the OCR and database directly from ESP page.
```
//==== on dylib
extern "C" {
    EXPORT
    const char*  getRecord(const char*db,int index){
          .... get record content ....
         return (???);
    }
}
//==== on ESP page
<% render(getRecord("BOOKS",1280));%>
```
Problem is we can not found any stable method to send memory buffer from library function to ESP.
It is need some way to send memory buffer directly to ESP function.
The only method we found it is use global variable in c++ code and send it address as return value to ESP
```
    string dataStr;
    const char*  getRecord(const char*db,int index){
          .... get record content ....
         dataStr=recordData;
         return dataStr.c_str();
    }
```
This is only a patch and not solution.  It is about 1/1500 chance to restart ESP by memory error.
Another way if we will declare buffer in ESP page and fill it in c++ function.  It is also very unstable and have about 1/20 chance to restart ESP.

```
//==== on dylib
extern "C" {
    EXPORT
    const char*  getRecord(const char*db,int index, char**buff){
          .... get record content ....
          *buff=(char*)calloc(dataSize,sizeof(char));
          memcpy(*buff,recordData,dataSize);
          return NULL;
    }
}
//==== on ESP page
<% 
char *buff;
getRecord("BOOKS",1280, &buff);
render(buff);
//free(buff);  -- buffer free restart ESP instantly
%>
```
Thank you all for your great work for all beings.
Merry Christmas!
Alexander

**Comment by dev-embedthis** [comment]
You can use memory from your library in your ESP code on an ESP thread provided the memory is not freed. You then need to decide who will free the memory. If you allocate the memory and give it to ESP , the ESP code can call free() on that memory without issue.

Net/Net: the ESP garbage collected memory and the garbage collector will never interfere with normal C/C++ malloc memory. If you malloc memory in your library, it is totally safe from the ESP garbage collector. Vice/versa, you should never call free() on ESP allocated memory.

**Comment by RimeOCRLIB** [comment]
For use common memory space with library it is need link it as static library. After that memory heap is the common space.
in esp.json config it is 
```
    esp: {
        app: true,
        static: true
    },
```
