### ISSUE TITLE
Json parsing failing

### ISSUE THREAD

**Issue by CristianIonutIonescu** [embedthis/esp#87]
### Environment

ESP version: 8.0.0 build from source and 7.0.2 build from source
O/S: Linux Ubuntu 16.04
Hardware PC
Customization: none

Configure command line:
`./configure`
(default build)

### Problem Description

When trying to parse a valid JSON the json parser fails to parse it.
### Sample:
```
{
    "myArray":[
        {
            "myEmptyObject":{

            }
        },
        {
            "myNonEmptyObject":{
                "x":1
            }
        }
    ]
}
```
I investigated the problem and the bug seems to be that the JSON parser does not know how to parse an empty JSON object.

### Code sample to reproduce the issue:

```
char *myJsonStr = "{\"myArray\":[{\"myEmptyObject\":{}},{\"myNonEmptyObject\":{\"x\":1}}]}";
MprJson *myJson;
const char *errMsg;
if ((myjson = mprParseJsonEx(myJsonStr , 0, 0, 0, &error_msg)) == 0) {
	mprLog("debug", 0 , "json '%s' not loaded: %s.",myJsonStr , errorMsg);
} else {
	mprLog("debug", 0 , "json loaded.");
}
```
### Error message:

`json '{"myArray":[{"myEmptyObject":{}},{"myNonEmptyObject":{"x":1}}]}' not loaded: JSON Parse Error: Expected property name At line 2. Token "{".`

**Comment by dev-embedthis** [comment]
Confirmed.

This is where you have an empty object inside an array.

Here is a quick (untested) fix:

```
@@ -12939,9 +12942,7 @@ static MprJson *jsonParse(MprJsonParser *parser, MprJson *obj)
                         return obj;
                     }
                 }
-                if (obj->type & MPR_JSON_OBJ) {
-                    parser->state = MPR_JSON_STATE_NAME;
-                }
+                parser->state = (obj->type & MPR_JSON_OBJ) ? MPR_JSON_STATE_NAME : MPR_JSON_STATE_VALUE;
```

**Comment by CristianIonutIonescu** [comment]
Thank you for your quick response!

I tested the fix and it seems to be ok. If any JSON parsing problems arise from it, I will post samples.
