### ISSUE TITLE
How to upload a file  to target board via esp?

### ISSUE THREAD

**Issue by abner-xie** [embedthis/esp#89]
I use official esp sample(upload) to test file uploading.[https://github.com/embedthis/esp/tree/dev/samples/upload](url)

when I run esp in Ubuntu, the result is shown in the figure. 
Now I don't known where the file transmit to.

 
![upload](https://user-images.githubusercontent.com/30360166/50418457-68d53380-0866-11e9-92c3-b3fd065d9a90.jpg)

**Comment by dev-embedthis** [comment]
the FILENAME variable points to the file.

You need to copy it from there.

**Comment by abner-xie** [comment]
Thanks, I got it




| |
abner_xie
邮箱：abner_xie@yeah.net
|

Signature is customized by Netease Mail Master

On 08/09/2019 10:32, Embedthis Development wrote:

Closed #89.
