### ISSUE TITLE
redirect SSL on another port

### ISSUE THREAD

**Issue by RimeOCRLIB** [embedthis/esp#90]
Good day. 
Please give any advice  how we can use ESP with certbot.eff.org SSL certificate  on port different from 443
We use apache and esp on the same macos server and https://hostname:443  send request to apache instead esp.
in esp.json we have 
 "ssl": {
            "certificate": "/private/etc/letsencrypt/archive/www.server.ru/fullchain1.pem",
            "key": "/private/etc/letsencrypt/archive/www.server.ru/privkey1.pem"
        },

Happy New Year!
Alexander

**Comment by dev-embedthis** [comment]
In your esp.json

"http": {
    "server": {
            listen: [
                "https://:4443",
            ],

Just specify the ports you want to listen on with "https"

**Comment by RimeOCRLIB** [comment]
Good evening. 
We have edited esp.json configuration file 
`
"server": {
        	"listen": "*:4000",
        	"listen": "https//:4443"  
	    },
	    "ssl": {
            "certificate": "/private/etc/letsencrypt/archive/www.buddism.ru/fullchain1.pem",
            "key": "/private/etc/letsencrypt/archive/www.buddism.ru/privkey1.pem" 
        },
`
How we can apply this esp.json  configuration file and listen IP address instead of localhost? 
If we start ESP by command
esp -v 
in program output is
Started HTTP service on 127.0.0.1:4000

If we force ip and port to serve 

esp -v 87.236.26.40:4443
in program output is 
Started HTTP service on 87.236.26.40:4443

esp read this esp.json configuration file, but serve 4443 port by HTTP, not by HTTPS.

How we need to solve this problem?

Thank you for any help.
Alexander
