### ISSUE TITLE
redirect http request to https port

### ISSUE THREAD

**Issue by RimeOCRLIB** [embedthis/esp#92]

**Comment by RimeOCRLIB** [comment]
Good day. 
After install SSL certificate and handle https request via 4443 port it is need redirect all 
http://domain.ru:4000
https://domain.ru:4443 
http://domain.ru:4443 

requests on https://domain.ru:4443
in esp.jason config file we have:

   redirect: [
	   {
		from: ':4443/',
		status: 301,
		to: 'https://'
	   },
	   {
		from: ':4000/',
		status: 301,
		to: 'https://'
	   }
   ]
but it is not have effect.
Any help and advice is greatly appreciated.

With best regards
Alexander 
www.buddism.ru

**Comment by dev-embedthis** [comment]
```
http: {
    redirect: "secure",
}
