### ISSUE TITLE
mprAllocFast(size_t usize) allocated block as function return in dynamic library

### ISSUE THREAD

**Issue by RimeOCRLIB** [embedthis/esp#94]
Good day.
We need return a lot of different data from c++ functions in OCR dynamic library for ESP.
Right now all we was able to found for stable work it is fixed size buffers which allocated in ESP and filled in c++ function. 
https://github.com/embedthis/esp/issues/86

According the MPR documentation we can allocate memory by mprAllocFast(size_t usize) and use this block as static.
But for now all attempt to allocate memory in C++ dynamic library code and return the pointer is failed.
```
//*** this is test code ******************************************
//in dynamic library
    EXPORT
    const char* helloVarStr(char *str) {
        stData="www";
        static char *msg=(char*)mprAllocFast(stData.size());
        memcpy(msg,(char*)&stData[0],stData.size());
        cout<<msg<<1<<endl; //msg  test print is fine
        return msg;
    }

// in ESP page 
const char* a=helloVarStr("www");
render("a =%s",a); 

//in ESP page render("a =%s",a);  failed with memory error.

// ****** this also not work ***************************************
//allocating memory in dynamic library failed
EXPORT
    const char* helloVarStr_alloc(char *str) {
        stData="www";
        char *msg=(char*)calloc(stData.size()+1, 1);
        memcpy(msg,(char*)&stData[0],stData.size());
        msg[stData.size()]=0;
        cout<<msg<<2<<endl; ; //msg  test print is fine
        return msg;
    }
//in ESP page render("a =%s",a);  failed with memory error.

//***** fixed buffer also not work in real site but working in test site ************
    EXPORT
    const char* helloVarStr(char *str) {
        stData="www";
        memcpy(str,(char*)&stData[0],stData.size());
        str[stData.size()]=0;
        cout<<str<<2<<endl; //msg  test print is fine
        return str;
    }
// this solution working in «one user» test site with static library linking
// in real site with 1 request  per second not working.
```
How we can use mprAllocFast(size_t usize) in c++ dynamic library?
Any help and advice is greatly appreciated.

Alexander

**Comment by RimeOCRLIB** [comment]
For use common memory space with library it is need link it as static library. After that memory heap is the common space. mprAllocFast also work fine.
in esp.json config it is 
```
    esp: {
        app: true,
        static: true
    },
```

**Comment by RimeOCRLIB** [comment]
In main site content we have the same error. Static linking not help, still have memory errors...

**Comment by RimeOCRLIB** [comment]
Update of the problem solution progress.
As result of the trial and error method application we have a working solution.
Any sharing of the memory between DLL and main program failed in 1/300 cases. So we transfer pointer on the HTTPConn main connection structure in DLL and render DLL functions result as memory buffer with set of data headers directly from DLL to HTTP port connection. 
```
//in OCRLibrary.h
#ifdef CPP_DYLIB
extern "C" {
#endif
   int renderCpp(void *conn,cchar* command)
#ifdef CPP_DYLIB
}
#endif

//in OCRLibrary.cpp DLL
#ifdef CPP_DYLIB
extern "C" {
#endif
  EXPORT
    int renderCpp(void *conn,cchar* command) {
            int      count;
           string msg; 
           //implementation of the C++ functions according the command
           init(command); //init  set of C++ objects according to command
           //render result msg to port
           // addHeader() - it is need
          httpSetHeaderString((HttpConn*)conn, "Content-Type", "image/png");
          httpAddHeader((HttpConn*)conn, "Content-Length", "%d", (int)msg.size());
          if(msg.size{
                count = (int)espRenderBlock((HttpConn*)conn, &msg[0], msg.size());
           }
           //c++ objects destructor
           freeMemory();
           return count;
#ifdef CPP_DYLIB
}
#endif

///_______ in ESP page ___________
#include "OCRLibrary.h"
renderCPP(getConn(),"searchTextCorpus");

```
This configuration serve few days 1 request/sec without need to reboot

**Comment by dev-embedthis** [comment]
Regarding mprAlloc and AllocFast, those will return memory that must be retained otherwise the garbage collector will reclaim.

Read this for details: https://www.embedthis.com/appweb/doc/ref/memory.html

i.e. you must retain a pointer to the memory that is "marked" via mprMark.
