### ISSUE TITLE
websocket memory leak

### ISSUE THREAD

**Issue by abner-xie** [embedthis/esp#95]
Hello, in our projects, we used websocket protocol for data transfering. Reference to official demo, function 
httpSendBlock is used to response web clients websocket request every 3 seconds. But, when esp process runs beyond 6 hours, it will be killed by system. We monitor the memory usage of esp, it has been increasing. How I solve this problem?

**Comment by dev-embedthis** [comment]
We've not seen this in our tests.

Can you create a minimal test esp app that we could use to replicate?

**Comment by abner-xie** [comment]
I'm sorry, esp doesn't exist memory leak, which because of using cJson_Print function. It will malloc memory to copy strings but not free.  It need user free.




| |
abner_xie
邮箱：abner_xie@yeah.net
|

Signature is customized by Netease Mail Master

On 08/09/2019 10:27, Embedthis Development wrote:

We've not seen this in our tests.

Can you create a minimal test esp app that we could use to replicate?

**Comment by abner-xie** [comment]
So this issue could be closed.




| |
abner_xie
邮箱：abner_xie@yeah.net
|

Signature is customized by Netease Mail Master

On 08/09/2019 20:51, abner-xie wrote:
I'm sorry, esp doesn't exist memory leak, which because of using cJson_Print function. It will malloc memory to copy strings but not free.  It need user free.




| |
abner_xie
邮箱：abner_xie@yeah.net
|

Signature is customized by Netease Mail Master

On 08/09/2019 10:27, Embedthis Development wrote:

We've not seen this in our tests.

Can you create a minimal test esp app that we could use to replicate?
