### ISSUE TITLE
GPL 2.0 requirements incorrectly stated in license

### ISSUE THREAD

**Issue by PaluMacil** [embedthis/esp#96]
Your license readme states that you are providing this source code with two licenses, one being GPL 2.0. You state incorrectly that "you must offer your source code to the general public and anyone who requests it" and go on yo say that "Embedthis hereby requests a copy of your source code that is used in combination with ESP."

However, GPL 2.0 only requires (from the preamble) "if you distribute copies of such a program, whether gratis or for a fee, you must give the recipients all the rights that you have. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights" but never indicates that you are compelled to distribute a copy of the program in the first place. Furthermore, it goes on to say that you "You may not impose any further restrictions on the recipients' exercise of the rights granted herein." I believe you must either cease claiming that your software is licensed as a GPL 2.0 or make more clear that you are not adding additional requirements.

The reason that I find your request for source concerning is that if I were to make a modification of ESP, I would add code to my fork that is also GPL 2.0 licensed but I would not be willing to assign you copyright over my work because you might choose to incorporate the code into what you distribute under your commercial license. This would be a violation of my copyright and this illegal even though you'd be perfectly able to integrate it into your GPL code.

All this said, I am not primarily a C developer, so my own use of this project is likely to be experimental and uninteresting to you, but I don't want to see you either open yourself up to either copyright violation against a fork or see GPL 2.0 misrepresented. Certainly I think a couple of small tweaks to your language (i.e. dropping the implication that people must give you access to source and even perhaps that you might use this source without permission) will lead to continued business success. I'm also sure that a proper representation of GPL 2.0 will encourage people to even sign a copyright assignment so that their code can be used in both your GPL and commercial products. I do that myself with a number of companies that offer open source projects.

**Comment by dev-embedthis** [comment]
The LICENSE.md should add "if you distribute". The appweb LICENSE.md does that. 

Regarding your situation. If you fork, make changes and distribute ESP under the GPL, then you must make the source code freely available. Similarly if you create a derivative work without modifying ESP, you must make your source code freely available. If you do not distribute your work, then you do not need to share the source code.

Many companies use ESP and Appweb and do not make the derivative works licensed under the GPL freely available in source form. The request in our LICENSE.md document is a request, under the GPL for free access to the source code of any such derivative works. This is not an additional term to the GPL, but rather a request according to the GPL for access to the source code of the derivative works.

Note: this has nothing to do with copyright.

**Comment by PaluMacil** [comment]
Again, my intent is discussion and not to actually distribute a product.

That said, I do feel that the request cannot be binding. To my understanding, the GPL obligation to provide source is only relevant to parties that you distribute to. If I don't give you a binary but give others a binary, I don't need to honor your request (according to the GPL) since you didn't get a binary--though the others I distributed to could certainly give you the source freely.

Copyright, at least in the United States, is very relevant. If you're not familiar, I recommend you study up to be safe. Even though licensing is a different topic, the ownership of copyright conveys the very right to license something. If I write some GPL code, you can use it in your GPL product regardless of whether it is for another project or a derivative of yours. However, if you want to use that GPL code you merged in your commercial product, you would want to have asked me for an assignment of copyright because without that, you would be violating my copyright. By licensing it under something that the GPL is not compatible (a commercial license) with without the right to license the code, it would be a liability to you.

What I'm suggesting is that people would probably be willing to contribute to your GPL codebase while assigning you copyright (companies like Google, Microsoft, etc do this for all of their open projects--it's usually called a contributor license agreement and can vary in what it does exactly) so that you could thrive as a company and use the contributions under both licenses.

I'll close this issue to not spend any more of your valuable time, but my suggestion remains that it would be clearer to request that people upstream their improvements to the product and sign a CLA.

**Comment by dev-embedthis** [comment]
Thanks for your thoughts. We do have a CLA and do take enhancements from users for that purpose. Agree with you in this regard. We don't do assignment of copyright, but do request that users license their copyright portions using an MIT license.

However you do misstate the GPL.

If you distribute an integrated product with ESP, then you must make the source code freely available to all. Not just to those that you distribute to. i.e. anyone may ask for the source code which must be provided. This is the source to the entire integrated product ESP + other code.
